apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: team-red
  name: team-red
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: team-red
    spec:
      containers:
      - image: team-red
        name: team-red
        imagePullPolicy: Never
        ports:
        - containerPort: 3003
        resources: {}
        envFrom:
          - configMapRef:
              name: team-red
            prefix: TEAM_RED_
        env:
          - name: TEAM_RED_SENTRY_DNS
            valueFrom:
              secretKeyRef:
                name: team.red
                key: sentry.dns
status: {}
